In [1]:
import pandas as pd

In [2]:
sudeste_path = '../data/parquet/regiao/SUL.parquet'
df = pd.read_parquet(sudeste_path)
df.head()

,Nome do RCBP,Sexo,Data de Nascimento,Idade,Raca/Cor,Nacionalidade,Naturalidade Estado,Naturalidade,Grau de Instrução,Estado Civil,...,Lateralidade,Estadiamento,TNM,Status Vital,Tipo do Obito,Data do Óbito,Data de Último Contato,Data de Diagnostico,Metástase à distância,Regiao
360524,RCBP CURITIBA,MASCULINO,28/09/1933,62.0,BRANCO,BRASIL,Não informado,None,SEM INFORMAÇÃO,SEM INFORMAÇÃO,...,None,nan,nan,None,CÂNCER,21/04/1998,None,01/04/1996,None,SUL
494715,RCBP PORTO ALEGRE,FEMININO,19/08/1927,65.0,BRANCO,BRASIL,Não informado,Não Informado,SEM INFORMAÇÃO,VIÚVO,...,None,nan,nan,None,CÂNCER,12/05/2018,None,23/04/1993,None,SUL
494716,RCBP PORTO ALEGRE,FEMININO,17/01/1934,59.0,BRANCO,BRASIL,RIO GRANDE DO SUL,None,FUNDAMENTAL II (5ª A 8ª SÉRIE),SEM INFORMAÇÃO,...,None,nan,nan,None,SEM INFORMAÇÃO,25/09/1994,None,05/07/1993,None,SUL
494717,RCBP PORTO ALEGRE,FEMININO,24/10/1939,54.0,BRANCO,Não informado,Não informado,Não Informado,SEM INFORMAÇÃO,SOLTEIRO,...,None,nan,nan,None,SEM INFORMAÇÃO,28/04/1994,None,11/12/1993,None,SUL
494718,RCBP PORTO ALEGRE,MASCULINO,09/05/1920,72.0,BRANCO,Não informado,Não informado,Não Informado,SEM INFORMAÇÃO,SEM INFORMAÇÃO,...,None,nan,nan,None,CÂNCER,26/06/2019,None,09/02/1993,None,SUL

In [3]:
df.shape

(273439, 37)

In [4]:
df['Data de Diagnostico'].count()

273439

In [5]:
df['Data de Diagnostico'] = pd.to_datetime(df['Data de Diagnostico'], format='%d/%m/%Y')

In [6]:
df['Data de Diagnostico'].count()

273439

In [7]:
df = df.sort_values(by='Data de Diagnostico')

In [8]:
df.head()

,Nome do RCBP,Sexo,Data de Nascimento,Idade,Raca/Cor,Nacionalidade,Naturalidade Estado,Naturalidade,Grau de Instrução,Estado Civil,...,Lateralidade,Estadiamento,TNM,Status Vital,Tipo do Obito,Data do Óbito,Data de Último Contato,Data de Diagnostico,Metástase à distância,Regiao
496900,RCBP PORTO ALEGRE,FEMININO,05/01/1947,45.0,BRANCO,Não informado,Não informado,None,SEM INFORMAÇÃO,SEM INFORMAÇÃO,...,None,nan,nan,None,SEM INFORMAÇÃO,11/03/1995,None,1993-01-01,None,SUL
495869,RCBP PORTO ALEGRE,FEMININO,18/11/1911,81.0,BRANCO,Não informado,Não informado,None,SEM INFORMAÇÃO,SEM INFORMAÇÃO,...,None,nan,nan,None,SEM INFORMAÇÃO,31/12/1993,None,1993-01-01,None,SUL
495267,RCBP PORTO ALEGRE,FEMININO,22/01/1950,42.0,INDÍGENA,Não informado,Não informado,None,SEM INFORMAÇÃO,SEM INFORMAÇÃO,...,None,nan,nan,None,SEM INFORMAÇÃO,07/08/1993,None,1993-01-01,None,SUL
496631,RCBP PORTO ALEGRE,FEMININO,28/10/1928,64.0,BRANCO,Não informado,Não informado,None,SEM INFORMAÇÃO,SEM INFORMAÇÃO,...,None,nan,nan,None,SEM INFORMAÇÃO,17/06/1993,None,1993-01-01,None,SUL
497069,RCBP PORTO ALEGRE,MASCULINO,20/03/1945,47.0,BRANCO,BRASIL,Não informado,None,SEM INFORMAÇÃO,SEM INFORMAÇÃO,...,None,nan,nan,None,SEM INFORMAÇÃO,07/04/1998,None,1993-01-01,None,SUL

In [9]:
df.tail()

,Nome do RCBP,Sexo,Data de Nascimento,Idade,Raca/Cor,Nacionalidade,Naturalidade Estado,Naturalidade,Grau de Instrução,Estado Civil,...,Lateralidade,Estadiamento,TNM,Status Vital,Tipo do Obito,Data do Óbito,Data de Último Contato,Data de Diagnostico,Metástase à distância,Regiao
2158723,RCBP CURITIBA,FEMININO,14/06/1930,88.0,BRANCO,BRASIL,Não informado,None,MÉDIO (ANTIGO SEGUNDO GRAU),VIÚVO,...,SEM INFORMAÇÃO,99 - SEM INFORMAÇÃO,999,MORTO,CÂNCER,31/12/2018,31/12/2018,2018-12-31,None,SUL
2152236,RCBP CURITIBA,FEMININO,20/01/1936,82.0,AMARELA,BRASIL,Não informado,None,SEM ESCOLARIDADE,VIÚVO,...,SEM INFORMAÇÃO,99 - SEM INFORMAÇÃO,999,MORTO,CÂNCER,31/12/2018,31/12/2018,2018-12-31,None,SUL
2159762,RCBP CURITIBA,MASCULINO,04/05/2007,11.0,PARDA,BRASIL,Não informado,None,FUNDAMENTAL II (5ª A 8ª SÉRIE),SOLTEIRO,...,NÃO SE APLICA,99 - SEM INFORMAÇÃO,999,MORTO,CÂNCER,31/12/2018,31/12/2018,2018-12-31,None,SUL
2155346,RCBP CURITIBA,MASCULINO,20/09/1931,87.0,AMARELA,JAPAO,Não informado,Não Informado,FUNDAMENTAL II (5ª A 8ª SÉRIE),CASADO,...,SEM INFORMAÇÃO,99 - SEM INFORMAÇÃO,999,MORTO,CÂNCER,31/12/2018,31/12/2018,2018-12-31,None,SUL
2154739,RCBP CURITIBA,FEMININO,29/08/1948,70.0,BRANCO,BRASIL,PARANÁ,CURITIBA,FUNDAMENTAL I (1ª A 4ª SÉRIE),CASADO,...,ESQUERDA,99,999,VIVO,None,None,24/04/2019,2018-12-31,None,SUL

In [13]:
print(df['Data de Diagnostico'].min())
print(df['Data de Diagnostico'].max())

datas = pd.date_range(start='1993-01-01', end='2018-12-31', freq='ME')

1993-01-01 00:00:00
2018-12-31 00:00:00

In [14]:
print(len(datas))

312

In [15]:
n_unique_months = df['Data de Diagnostico'].dt.to_period('M').nunique()

print(n_unique_months)

312

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 273439 entries, 496900 to 2154739
Data columns (total 37 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Nome do RCBP                      273439 non-null  object
 1   Sexo                              273439 non-null  object
 2   Data de Nascimento                246437 non-null  object
 3   Idade                             268267 non-null  float64
 4   Raca/Cor                          273439 non-null  object
 5   Nacionalidade                     268543 non-null  object
 6   Naturalidade Estado               268597 non-null  object
 7   Naturalidade                      102722 non-null  object
 8   Grau de Instrução                 268539 non-null  object
 9   Estado Civil                      264012 non-null  object
 10  Código Profissão                  251484 non-null  float64
 11  Nome Profissão                    251484 non-null  object
 12  Estado Endereço                   273418 non-null  object
 13  Cidade Endereço                   273439 non-null  object
 14  Descrição da Topografia           273439 non-null  object
 15  Código da Topografia              273439 non-null  object
 16  Descrição da Morfologia           273439 non-null  object
 17  Código da Morfologia              273439 non-null  float64
 18  Descrição da Doenca               273439 non-null  object
 19  Código da Doenca                  273439 non-null  object
 20  Descrição da Doenca Infantil      3855 non-null    object
 21  Código da Doenca Infantil         3855 non-null    object
 22  Descrição da Doenca Adulto Jovem  7436 non-null    object
 23  Código da Doenca Adulto Jovem     7436 non-null    object
 24  Indicador de Caso Raro            273439 non-null  bool
 25  Meio de Diagnostico               273439 non-null  object
 26  Extensão                          273439 non-null  object
 27  Lateralidade                      39322 non-null   object
 28  Estadiamento                      273439 non-null  object
 29  TNM                               273439 non-null  object
 30  Status Vital                      68954 non-null   object
 31  Tipo do Obito                     121480 non-null  object
 32  Data do Óbito                     121480 non-null  object
 33  Data de Último Contato            62755 non-null   object
 34  Data de Diagnostico               273439 non-null  datetime64[ns]
 35  Metástase à distância             1321 non-null    object
 36  Regiao                            273439 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(3), object(32)
memory usage: 77.4+ MB